version: "3"
services:
    db: # db ip 172.25.0.101
        image: mysql:5.7
        #environment: moved to file
        #    MYSQL_ROOT_PASSWORD: root
        #    MYSQL_USER: vapor
        #    MYSQL_PASSWORD: test
        #    MYSQL_DATABASE: test
        env_file:
          - database.env

        volumes:
          - db_data

        #networks:
        #  - internal

        restart: always

    api:
        image: docker.pkg.github.com/pascalboehler/wsie-api/wsieapi:latest
        depends_on:
          - db
        # ports:
        #     - 8080:8080
        #     - 80:80

        #networks:
        #  - internal

        links:
          - "db:database"

        restart: always

        labels:
          - traefik.http.routers.api.rule=Host("wsiedevapi.uksouth.cloudapp.azure.com") # change to server dns name
          #- traefik.http.routers.api.rule=Host("localhost") # for testing on local system
          #- traefik.http.services.api.loadBalancer.stickiness


    grafana:
        image: grafana/grafana:latest
        #networks:
        #  - internal
        environment:
          - GF_SERVER_ROOT_URL=http://wsiedevapi.uksouth.cloudapp.azure.com/grafana # for server
          #- GF_SERVER_ROOT_URL=http://localhost/grafana # for local testing
        restart: always
        labels:
          #- traefik.http.routers.grafana.rule=Host("wsiedevapi.uksouth.cloudapp.azure.com") && PathPrefix("/grafana")
          - traefik.http.routers.grafana.rule=Host("localhost") && PathPrefix("/grafana") # for testing on local system

    reverse-proxy:
      # The official v2.0 Traefik docker image
      image: traefik:v2.0
      # Enables the web UI and tells Traefik to listen to docker
      command: --api --providers.docker
      restart: always
      ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api)
        - "8080:8080"
      volumes:
        # So that Traefik can listen to the Docker events docker socket is linked to service
        - /var/run/docker.sock:/var/run/docker.sock

    portainer:
      image: portainer/portainer
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host("localhost") && PathPrefix("/portainer")

volumes:
  db_data: { }
  portainer_data: { }