version: "3"
services:
    db: # db ip 172.25.0.101
        image: mysql:5.7
        #environment:
        #    MYSQL_ROOT_PASSWORD: root
        #    MYSQL_USER: vapor
        #    MYSQL_PASSWORD: test
        #    MYSQL_DATABASE: test
        env_file:
          - database.env

        networks:
          - internal

        restart: always

    api:
        image: docker.pkg.github.com/pascalboehler/wsie-api/wsieapi:latest
        depends_on:
          - db
        #ports:
        #    - 8080:8080
        #    - 80:80

        #networks:
        #  - internal

        links:
          - "db:database"

        labels:
          - traefik.http.routers.api.rule=Host('wsiedevapi.uksouth.cloudapp.azure.com')
          - traefik.http.services.api.loadBalancer.stickiness


    grafana:
      image: grafana:latest
      networks:
        - internal
      labels:
        - traefik.http.routers.api.rule=Host('wsiedevapi.uksouth.cloudapp.azure.com') && PathPrefix('/grafana')

    traefik:
        image: traefik:v2.0
        command: --providers.docker
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
          - 80:80
          - 443:443
        #networks:
        #  - internal

#networks:
#  internal:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.50.0.0/24
